// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/24/2026, 1:20:29 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/codi/Desktop/ig-repo/e-commerces/E3BYTE/sc_e3b_store_loukdo/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/codi/Desktop/ig-repo/e-commerces/E3BYTE/sc_e3b_store_loukdo/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/codi/Desktop/ig-repo/e-commerces/E3BYTE/sc_e3b_store_loukdo/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/codi/Desktop/ig-repo/e-commerces/E3BYTE/sc_e3b_store_loukdo/app/plugins/**/*.{js,ts,mjs}","/home/codi/Desktop/ig-repo/e-commerces/E3BYTE/sc_e3b_store_loukdo/app/composables/**/*.{js,ts,mjs}","/home/codi/Desktop/ig-repo/e-commerces/E3BYTE/sc_e3b_store_loukdo/app/utils/**/*.{js,ts,mjs}","/home/codi/Desktop/ig-repo/e-commerces/E3BYTE/sc_e3b_store_loukdo/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/codi/Desktop/ig-repo/e-commerces/E3BYTE/sc_e3b_store_loukdo/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/codi/Desktop/ig-repo/e-commerces/E3BYTE/sc_e3b_store_loukdo/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/codi/Desktop/ig-repo/e-commerces/E3BYTE/sc_e3b_store_loukdo/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;